# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 15:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0004_auto_20170627_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 27, 15, 47, 54, 816386, tzinfo=utc)),
        ),
    ]
